# Generated by Django 3.2 on 2023-11-19 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(help_text='Ingredient quantity', validators=[django.core.validators.MinValueValidator(limit_value=0, message='Количество ингредиента не может быть быть равно или меньше 0')], verbose_name='Quantity'),
        ),
    ]
