# Generated by Django 3.2 on 2023-11-19 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_ingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(help_text='Ingredient quantity', validators=[django.core.validators.MinValueValidator(limit_value=0.01, message='Количество ингредиента не может быть быть равно или меньше 0')], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Link to picture', upload_to='recipes/images/', verbose_name='Picture'),
        ),
    ]
