# Generated by Django 3.2 on 2023-11-19 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20231119_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(help_text='Ingredient quantity', validators=[django.core.validators.MinValueValidator(limit_value=0.01, message='The quantity of the ingredient cannot be equal to or less than 0')], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Cooking time (minutes)', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Cooking time cannot be less than 1 minute')], verbose_name='Cooking time'),
        ),
    ]
