# Generated by Django 3.2 on 2023-11-19 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_to_user',
            field=models.ForeignKey(help_text='User subscribe to', on_delete=django.db.models.deletion.CASCADE, related_name='to_user_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(help_text='User who subscribes', on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
